changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Fixes
      labels:
        - bug
    - title: Improvements
      labels:
        - enhancement
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - "*"
